### ISSUE TITLE
PhantomJS dependency

### ISSUE THREAD

**Issue by avitalp** [bevacqua/hit-that#1]
Hey there,

Quick note, if you're receiving the following error:

```
/usr/lib/node_modules/hit-that/index.js:22
      throw err;
            ^
Error: /usr/lib/node_modules/hit-that/node_modules/webshot/node_modules/phantomjs/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
```

It's because PhantomJS has a dependency on `libfontconfig`, which was missing on my system.

I was able to fix it simply with: `sudo apt-get install libfontconfig`

**Comment by bevacqua** [comment]
Thanks, could you please report this over to `phantomjs`? Not really an issue with `hit-that` per se

**Comment by avitalp** [comment]
Sure thing. Was more of a helpful "install note" than bug report :)
