### ISSUE TITLE
Add flag --full to automatically fill the terminal width

### ISSUE THREAD

**Issue by felippenardi** [bevacqua/hit-that#4]
Hello,

I'm wondering if you'd appreciate a `--full` flag for the CLI where it automatically use the number of columns on the current terminal.

Example: If your terminal is using 178 columns, calling `ht --full` would be the same as calling `ht --cols 178`.

Let me know if you think that makes sense and I'd love to work on that.

**Comment by bevacqua** [comment]
Sure. You can use `process.stdout.columns`.
