### ISSUE TITLE
windows console?

### ISSUE THREAD

**Issue by dirad** [bevacqua/hit-that#5]
tried in windows command prompt:
![ht ponyfoo 2](https://cloud.githubusercontent.com/assets/12030851/11179311/1f79e6fc-8c5b-11e5-9b9f-c0739ffec1ed.jpg)

and in conEmu which is a better console:
![ht ponyfoo 1](https://cloud.githubusercontent.com/assets/12030851/11179314/22e696a0-8c5b-11e5-87ac-d87527add2b9.jpg)

**Comment by bevacqua** [comment]
Take it up with `picture-tube`

**Comment by dirad** [comment]
@bevacqua what is `picture-tube`?  
Can you point me in the right direction or give any other info?
