### ISSUE TITLE
png-node is breaking

### ISSUE THREAD

**Issue by sallar** [bevacqua/hit-that#6]
hi, not sure what is causing this issue. ~it maybe because im using SSL?~ but yeah, `png-node` breaks when trying to use this tool with my website.

Shell: **Fish**
OS: **macOS Sierra**
Terminal: **Hyper**

![image](https://cloud.githubusercontent.com/assets/768052/21544876/8bbf45f6-cddb-11e6-8fe3-1345cf8d166f.png)

**Update:** I tried other SSL websites, they work fine.

**Comment by bevacqua** [comment]
May be that `webshot` is failing to produce a well-formed PNG file?

**Comment by sallar** [comment]
@bevacqua could be. my website is pretty simple though. I can dig into this later

**Comment by sallar** [comment]
@bevacqua issue was with the web-server. sorry for wasting your time!
